name: scions
recipe: pantheon
config:
  framework: drupal8
  site: scions
  id: 29af9bf2-a2f7-48cd-a0cd-884ab4b52ca6
services:
  appserver:
    webroot: web
    xdebug: true
  node-cli:
    type: 'node:6.10'
    globals:
      gulp-cli: latest
tooling:
  npm:
    service: node-cli
  node:
    service: node-cli
  gulp:
    service: node-cli
