logo:
  path: themes/custom/scions/logo.png
  use_default: 0
_core:
  default_config_hash: 5IeLRlPyZCikPqswOZcx9XvwgNJiVWU-Mbz2uxNSP9s
features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
background_file:
  - '5'
favicon:
  use_default: 1
